### ISSUE TITLE
trying to add libflashplayer.so to the appimage

### ISSUE THREAD

**Issue by MartinEtcheverry** [srevinsaju/Firefox-Appimage#11]
Maybe you have any idea on how to do that? i am adding libflashplayer.so but is not working . 
This will be extremely useful , to have for old solutions "flash only" (like vcloud director 8.20 in my case)

**Comment by srevinsaju** [comment]
@MartinEtcheverry do you know if `libflashplayer` is open source? If it is, I can certainly add it to the AppImage.

**Comment by plirof** [comment]
Flash player browser support has stopped so It won't work. There is a workarround in chrome by adding an extra extension (that re-enables support for flash) but I don't know if this can be done for firefox.

**Comment by srevinsaju** [comment]
Closing this ticket as `wontfix`
