### ISSUE TITLE
let mozilla release officially with your help

### ISSUE THREAD

**Issue by zivian** [srevinsaju/Firefox-Appimage#12]
@srevinsaju can you please upstream your work and let mozilla release it officially by discussing or submitting patches at [1249971](https://bugzilla.mozilla.org/show_bug.cgi?id=1249971)

**Comment by srevinsaju** [comment]
We have been working with MZLA Technologies to release Mozilla Thunderbird AppImage, first. Once Thunderbird AppImage becomes official, we can replicate the same technology for Firefox too.

See https://bugzilla.mozilla.org/show_bug.cgi?id=1703867

**Comment by zivian** [comment]
@srevinsaju thank you. its good news.
i am closing this.
