### ISSUE TITLE
🐞: Can't take screenshot on firefox

### ISSUE THREAD

**Issue by joe733** [srevinsaju/Firefox-Appimage#14]
As mentioned on the [mozzilla support page](https://support.mozilla.org/en-US/kb/take-screenshots-firefox?redirectslug=firefox-screenshots&redirectlocale=en-US) I've tried using the shortcut <kbd>Ctrl</kbd> + <kbd> Shift </kbd> + <kbd> S </kbd> but that didn't work. Clicking on screenshot tool after putting on the toolbar does nothing. Here's my related `about:config` 

![image](https://user-images.githubusercontent.com/38415384/116783703-ee5bf480-aaad-11eb-8652-aa0a85e30872.png)

Toggling the last option doesn't help. I can confirm it works on FIrefox debian package, with the same config.

Firefox: `v88`
System: `Arch Linux x86_64`

**Comment by srevinsaju** [comment]
It works for me on Firefox Nightly.

**Comment by joe733** [comment]
Yes, it does, but I don't think it is a bug with Firefox stable release, probably with the stable AppImage or some config I'm not sure which... Btw, the nightly UI looks cool.

**Comment by srevinsaju** [comment]
Agreed, distro's patch original Firefox sources to enable some extra features which might be disabled on the official builds. Firefox AppImage is built from the official firefox binary. Its likely Debian did something extra, to make the Firefox screenshot work on the stable version. 

> Btw, the nightly UI looks cool.

Agreed, Firefox Proton redesign
