### ISSUE TITLE
Runs from App Grid, but won't run from the favourites in Dash

### ISSUE THREAD

**Issue by chdslv** [srevinsaju/Firefox-Appimage#16]
Installed Firefox through zap and added the path too. Icon appeared on the App-grid (Ubuntu 21.10), Firefox runs quite well from there, but if added to favourites, that is to Dash, it won't run from there. 

![Screenshot from 2021-10-18 14-13-43](https://user-images.githubusercontent.com/28350701/137729215-18d9e260-22ba-4c1c-9fc0-6f0278359656.png)
The cursor (blue) keeps on turning. Remove the Firefox icon from from favourites, it runs again.

**Comment by chdslv** [comment]
Yes, on Gnome Wayland, which is the default on Ubuntu 21.10

**Comment by srevinsaju** [comment]
Can you try the newer version of `zap`? Looks like the problem was fixed here
