### ISSUE TITLE
 Sound Decoding problem

### ISSUE THREAD

**Issue by Mustafamutar** [srevinsaju/Firefox-Appimage#17]
Hi everyone i tried the appimage but the sound doesn't work although the firefox version from the void repo works fine
here is warning that terminal show when i play a YouTube video  
```
[Child 6898, MediaDecoderStateMachine #1] WARNING: 7fe548cdd6a0 OpenCubeb() failed to init cubeb: file /builds/worker/checkouts/gecko/dom/media/AudioStream.cpp:324
[Child 6898, MediaDecoderStateMachine #1] WARNING: Decoder=7fe548172400 [OnMediaSinkAudioError]: file /builds/worker/checkouts/gecko/dom/media/MediaDecoderStateMachine.cpp:3980
```
here is my system 
```
Linux void-linux 5.13.19_1 x86_64 GNU/Linux
```
Sorry for my English

**Comment by srevinsaju** [comment]
Hmm, sorry I have no clue. Maybe a ticket to Firefox support might help, or otherwise it might be a driver issue.
