### ISSUE TITLE
Not really portable in Linux Mint 20.02 codename UMA

### ISSUE THREAD

**Issue by andreantunesb** [srevinsaju/Firefox-Appimage#18]
Hi, i intendt to use a higher portable mode, them i create a folder as the same name off executable plus .config. However the files and configuration ara still being saved in the home folder of my user. 

Thanks for the very good work!

**Comment by srevinsaju** [comment]
G'day! You should pass `--appimage-portable-home` and `--appimage-portable-config` to set the new home and config path. See `--appimage-help` for more information

**Comment by andreantunesb** [comment]
> G'day! You should pass `--appimage-portable-home` and `--appimage-portable-config` to set the new home and config path. See `--appimage-help` for more information

A few data ago i have learned the .home command. Until that i was using only .config command tô store personal configurations. Thanks for the advice!
