### ISSUE TITLE
Firefox-AppImage stands out .

### ISSUE THREAD

**Issue by cmatomic** [srevinsaju/Firefox-Appimage#2]
I changed the name of my repository so you can use the name Firefox-AppImage, your repository is better than mine so I recommend changing to Firefox-AppImage.
Thanks for your excellent job you had with the repository .

**Comment by srevinsaju** [comment]
@cmatomic Wow Thanks! How did you come to know of this repository?

**Comment by cmatomic** [comment]
@srevinsaju 
I was trying to find a solution to make an appimage of one of my repositories updateable related to "gh-releases-zsync"

**Comment by srevinsaju** [comment]
Renamed, and updated the `updateinformation` to point to new repository. Thanks :tada:
