### ISSUE TITLE
pdf download problem

### ISSUE THREAD

**Issue by CoinCheung** [srevinsaju/Firefox-Appimage#22]
Hi,

I am using archlinux with xfce4 desktop environment.

I downloaded `firefox-99.0.r20220411174855-x86_64.AppImage` and add executable to it: `chmod u+x firefox-99.0.r20220411174855-x86_64.AppImage`. Then I open up a pdf file, such as [this](https://arxiv.org/pdf/2207.07116.pdf). When I try to download it with the button
![pic](https://user-images.githubusercontent.com/22693362/182337324-42fe8047-55ae-4f6e-af12-5115be449e52.jpg)
 
There is no reaction at all, thus I cannot download this pdf file. Would you please tell me what is the cause of this, and would  you please fix it if it is the problem about this appimage?

**Comment by marc1uk** [comment]
same as #23

**Comment by srevinsaju** [comment]
Sorry, I am not able to reproduce it with the latest versions of Firefox ESR at least. let me know if this problem still exist. If it still exists, please continue the thread of #23
