### ISSUE TITLE
Why are updates disabled in release?

### ISSUE THREAD

**Issue by erasedhammer99** [srevinsaju/Firefox-Appimage#24]
Just wondering why the release Firefox appimage has its updates forcefully disabled through policies.

about:policies shows: ```DisableAppUpdate | true```

The settings page says: ```Updates disabled by your system administrator```

Any way around this? Thanks

**Comment by marc1uk** [comment]
i would imagine this is a feature of the fact that the appimage is a single 'executable' file, so it's not really possible to update AppImages in general? I think you need to download a new version when you want to update.

**Comment by antony-jr** [comment]
> i would imagine this is a feature of the fact that the appimage is a single 'executable' file, so it's not really possible to update AppImages in general? I think you need to download a new version when you want to update.

I think the updates inbuilt in Firefox is disabled because AppImage has it's own way of updating AppImages using so called delta update using zsync (i.e similar to rsync but over http). You can see the official tool to do this https://github.com/AppImage/AppImageUpdate

**Comment by srevinsaju** [comment]
I am marking this ticket as closed. AppImages are read-only squash-fuse images, and hence Firefox will not be able to update its own files. If this feature was enabled, Firefox would still download the updates, but the update is lost. As suggested by @antony-jr , you may use AppImageUpdate, or any other AppImage updating tools (or re-download the AppImage on a newer update.) See https://github.com/AppImageCommunity/awesome-appimage#package-managers for some awesome projects.
