### ISSUE TITLE
Change firefox profile

### ISSUE THREAD

**Issue by luisee** [srevinsaju/Firefox-Appimage#25]
Hello everyone.
When I run the Firefox AppImage it uses the default Firefox profile that I already had installed.
How could I change a new profile to link it to the AppImage?
I have tried adding a parameter to the AppImage: `--class NewProfile %u` but I have not had exist
Thanks for any help.

**Comment by srevinsaju** [comment]
Hey, please use `firefox --ProfileManager` to create a new profile, and use the `-P` flag to set the name of the profile.
