### ISSUE TITLE
FF-ESR appimage is not the updated one

### ISSUE THREAD

**Issue by IdolIcon** [srevinsaju/Firefox-Appimage#26]
Last regular FF-ESR is 102.4 since 17-Oct-2022.
But last appimage version of FF- ESR is 102.3 (since 12-Sept-2022).

**Comment by IdolIcon** [comment]
Last version of regular FF-ESR is now 102.5, but here your appimage is still 102.3.

No updates in two months!!  WTF?

**Comment by antony-jr** [comment]
> No updates in two months!! WTF?

Come on dude, that's not cool. He has no obligation to do free work. If you want the latest version then just fork this repo and start a build.

**Comment by IdolIcon** [comment]
_"Come on dude, that's not cool. He has no obligation to do free work"_

Certainly! And I have no obligation to be 'cool'.

An abandoned (or not...) project with no explanation, leaving an outdated application as critical on security as a well known web browser to be downloaded. This kind of things give open source bad reputation and turns finding proper open source software into a nightmare.

**Comment by antony-jr** [comment]
@IdolIcon I think this issue is resolved. Please mind your attitude. If you care so much about open source getting bad reputation, today that's because of you and not the repo owner. A friendly reminder would have been cool or a PR of what the author just fixed.

Here are the builds for firefox-esr -> https://github.com/srevinsaju/Firefox-AppImage/releases/tag/firefox-esr

Please close the issue. Have a nice day :+1:

**Comment by IdolIcon** [comment]
_"Please mind your attitude."_

Why? It worked.

_"A friendly reminder would have been cool "_

I did it ten days before, when I opened the issue. And that attitude didn't work...

_"Here are the builds for firefox-esr -> [https]...."_

No, thank you. There were more problems with these builds that weren't addressed (for example https://github.com/srevinsaju/Firefox-Appimage/issues/23), and now this... Sorry, but I don't trust this project anymore, it obvious that it is semi-abandoned.

**Comment by srevinsaju** [comment]
Sorry, I had been having final exams the whole month and I havent got time to catch up with all the issues yet. 

> I did it ten days before, when I opened the issue. And that attitude didn't work...

Here is the link to GitHub's Code of Conduct: https://docs.github.com/en/site-policy/github-terms/github-event-code-of-conduct

> Sorry, but I don't trust this project anymore, it obvious that it is semi-abandoned.

Alright.

**Comment by AaronTechnic** [comment]
@IdolIcon Beggars can't be choosers.

**Comment by ShrirajHegde** [comment]
>Why? It worked.

Who told you that you are entitled to any support? Show us where it says you have a claim to any support.

>but I don't trust this project anymore.

Oh no ! What will the opensource community do without the entitled jerk ?

People like you are the cancer to opensource community. 

There are thousands of dead/stale repos on GitHub, GitLab and many other places. All of them clearly indicate the last release dates and commit dates. If you have that kind of urgency, simplest thing is to figure out yourself. Nobody owes you replies or support especially when you are being a jerk. 

# Please don't associate yourself with opensource community.

**Comment by GodBleak** [comment]
> Why? It worked.

It's a matter of respect. Take a look at Github's [Community Guidelines](https://docs.github.com/en/site-policy/github-terms/github-community-guidelines)

Regarding respect:
> …remember to criticize ideas, not people. Share thoughtful, constructive criticism and **be courteous to those you interact with. If you’re unable to engage respectfully, consider taking a step back**… 

> I did it ten days before, when I opened the issue. And that attitude didn't work...

That doesn't entitle you to anything, least of all to demand updates from the maintainer. If you'd like to know what you are entitled to, read the license:

> THE SOFTWARE IS PROVIDED "AS IS"

Looks like you're entitled to the software, as it is. Not updates, not security patches, not even an acknowledgement from the authour. Don't act like you're owed anything more. 

You want OSS developers at your beck and call? Ask them what their hourly rate is.

**Comment by nisaea** [comment]
> _"Please mind your attitude."_
> 
> Why? It worked.

It's the kind of attitude that drives small projects from a slow pace to the maintainer not caring anymore because they can't be arsed to deal with people like you.

It kills projects. Plain and simple.

It wasn't even that long a delay, jfc. People have lives.

**Comment by cupkax** [comment]
@srevinsaju Could you please close this issue when you are free? The comments are going offtopic and derailing into nonsense. Cheers.

**Comment by haydenbbickerton** [comment]
> @IdolIcon kys nutjob

![holdup](https://user-images.githubusercontent.com/2454958/203186607-95089e24-4e9d-4414-9b02-5ddf72cca872.jpg)

That aimless toxicity is even worse than the entitled criticism of the OP. Yuck.

@srevinsaju you're doing great work! I've just sponsored you on GitHub - **thank you for contributing to open source.** It might not pay the rent just yet, but your GitHub profile is gonna get you a great job when you're out of school. Love to see it.

**Comment by srevinsaju** [comment]
Thanks everyone! That means a lot ❤️

I will keep trying my best to create great open source software for all.

 I am closing this issue, and locking the conversation. If this issue pops up later, please feel free to create an issue again. Thank you!
