### ISSUE TITLE
Separate repos for different each type of firefox build

### ISSUE THREAD

**Issue by ksharindam** [srevinsaju/Firefox-Appimage#27]
Firefox, Firefox Nightly, Firefox Beta and Firefox ESR all types of builds are being released in the same repo with different tags.
So, AppImage managers are not able to identify each releases. 
The result is when I use such app such as AppImagePool, and trying to download any firefox build (e.g Firefox ESR), it shows only Nightly build. Because these apps are supposed to fetch the latest release and Nightly Build is tagged as latest.

This will be solved if separate repos are created for each type of build.

**Comment by srevinsaju** [comment]
Sorry, that will bring in a lot of maintenance overhead. But feel free to fork the repository and set up separate builds for each repo.
