### ISSUE TITLE
PWA Support

### ISSUE THREAD

**Issue by FabianoLothor** [srevinsaju/Firefox-Appimage#28]
Is it possible to make the `.AppImage` files support PWA or is it available only for `.DEB` installations?

**Comment by srevinsaju** [comment]
It should be possible. Especially if you are using an AppImage integration tool like AppImageLauncher or [`zap`](https://github.com/srevinsaju/zap)

**Comment by FabianoLothor** [comment]
It's because currently isn't embedded into firefox, we need to install a secondary package:
- https://github.com/filips123/PWAsForFirefox

But I'll try and see if I can get it working.
