### ISSUE TITLE
icon Firefox not shown in appmenu Ubuntu  20.04

### ISSUE THREAD

**Issue by Lvaskz** [srevinsaju/Firefox-Appimage#4]
Hi, I have waiting this appimage for a long Time, thanks to bring it us.
I am using appimagelauncher to integrate my appimages to appmenus Ubuntu 20.04.
But the problem Is the Firefox icon Is mising.
Can you make Firefox appimage compatible with appimagelauncher.? 
https://github.com/TheAssassin/AppImageLauncher
AND this some tools to help 
https://github.com/TheAssassin/appimagelint

**Comment by srevinsaju** [comment]
AppImageLauncher, uses `libappimage`, Integration works for me, using `libappimage`. But, the icon will fail to load until the `GDK Pixbuf Loaders` and Icon cache is refreshed. A logout and login should solve the issue.

**Comment by Lvaskz** [comment]
Hi, no icons to  me after reboot, see:
[image: ksnip_20200927-012554.png]

**Comment by srevinsaju** [comment]
If I am right, your image did not get embedded on GitHub for some reason

**Comment by Lvaskz** [comment]
Look:
![ksnip_20200927-012554](https://user-images.githubusercontent.com/29207169/94363997-7777fc80-0083-11eb-8f75-65b05f3c2410.png)

**Comment by Lvaskz** [comment]
Any Idea?

**Comment by srevinsaju** [comment]
Will check why it does not work.

**Comment by srevinsaju** [comment]
@Lvaskz can you test again? I am afraid, I cannot reproduce your bug :(

**Comment by srevinsaju** [comment]
Closing this, as no response from author.

**Comment by joe733** [comment]
Hey, I'm facing the same issue but with Arch. I installed `fuse` and `appimagelauncher-lite-...-x86_64.AppImage` so I guess that avoids the need to install `libappimage`. But this is what I get:

![Screenshot_2021-04-25_19-53-38](https://user-images.githubusercontent.com/38415384/115997519-fa087080-a600-11eb-8aaf-2ab0edd4cb04.png)

I wonder why other AppImages like Zoom, Motrix etc. are generating icons but not Firefox. I logged out and logged back in, even tried a restart and did the same after installing `libappimage` too but no Firefox icons are generated. As you can see the is show well on the `Window Buttons` (xfce panel plugin) but no where else.

I can change the icon but editing the `Icon=` line in the desktop file:
```
Exec=/home/jovial/Applications/firefox-87.0.r20210318103112-x86_64_1872cf635748cee87697ce80ae87be7f.AppImage %u
Icon=appimagekit_f83c47af27c4cb3402b24a0c1dc90cfb_firefox
Terminal=false
```
but then that won't align with the theme. Can you please help to figure this out?

**Comment by joe733** [comment]
| ![Screenshot_2021-04-25_21-40-14](https://user-images.githubusercontent.com/38415384/116000718-f8de4000-a60e-11eb-971a-689fdfe142e0.png) | ![Screenshot_2021-04-25_21-39-54](https://user-images.githubusercontent.com/38415384/116000711-f54ab900-a60e-11eb-9a13-f6ef7e716aa2.png) |
| --- | --- |

Change in WM_CLASS https://github.com/srevinsaju/Firefox-Appimage/pull/13, note the icon behaviour.

**Comment by srevinsaju** [comment]
This is probably not a bug in Firefox-AppImage's desktop files, as it is directly copied from the [Arch Linux's package source files](https://github.com/archlinux/svntogit-packages/blob/packages/firefox/trunk/firefox.desktop#L122). It looks like a bug, or a scope for a good feature request in [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher) instead.

cc @TheAssassin

**Comment by TheAssassin** [comment]
libappimage is unhappy about the lack of icons in `usr/share/icons`, as far as I can see. Perhaps you need to generate some from some `.svg`. The `.DirIcon` seems to be alright, but libappimage apparently doesn't want to use it.

```
> identify squashfs-root/firefox-beta.png 
squashfs-root/firefox-beta.png PNG 128x128+0+0 DirectClass 8-bit 13.2Ki 0.000u 0m:0.000004s
```

**Comment by akza07** [comment]
I'm having same issue. Any fix for it?

![image](https://user-images.githubusercontent.com/30655539/176350460-70f080db-363c-4545-aecb-b2defd746352.png)

**Comment by akza07** [comment]
Firefox nighly is the appimage, Works without issues but icon is not detected.
