### ISSUE TITLE
Creates a new profile every time it starts?

### ISSUE THREAD

**Issue by anssisaari** [srevinsaju/Firefox-Appimage#7]
I noticed this seems to create a new empty profile every time it starts? I scripted around that but is it supposed to work like that or is it a bug?

**Comment by srevinsaju** [comment]
No its not supposed to work like that. Are you sure you are having the latest version? I fixed it a week ago.

**Comment by anssisaari** [comment]
Sorry, I didn't check if it was working now before opening the issue. So yes, it's fine now. I started with -P and selected my profile as default and can now start without -P and the correct profile is loaded.
