### ISSUE TITLE
Adding policies.json

### ISSUE THREAD

**Issue by abdullah-if** [srevinsaju/Firefox-Appimage#9]
Adding distribution/policies.json will prevent the notification to update.
``` 
{
  "policies": {
    "DisableAppUpdate": true
  }
}
```

After:
![Screenshot_20201220_200213](https://user-images.githubusercontent.com/54185653/102715292-9a225600-42fe-11eb-88a4-c26b4689e349.png)

Before:
![Screenshot_20201220_200309](https://user-images.githubusercontent.com/54185653/102715294-9c84b000-42fe-11eb-9682-66505ae04d32.png)
Or add method to update as soon as a new release come, so it will not attempt to update by ownself.

P.S.: It seems that it applies update if extracted and directs to Firefox download page if kept as .appimage

**Comment by srevinsaju** [comment]
Interesting, Thanks for the information. I was looking for a method to disable the update thingy, but I couldn't find any much info. Thanks for letting me know. I will attribute the commit to you, kudos for finding it, and letting me know :smile: :+1:
